version: '3.8'
services:
  user-service:
    image: user-service:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      USER_SERVICE_PORT: ${USER_SERVICE_PORT:-8083}
      USER_SERVICE_API_KEY: ${USER_SERVICE_API_KEY:-03918417-a69a-4a49-95e1-48939efeefdb}
    ports:
      - '${USER_SERVICE_PORT:-8083}:${USER_SERVICE_PORT:-8083}'
    depends_on:
      - postgres
    networks:
      - user-service-network

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - user-service-network

  resource-service:
    image: resources-service:latest
    environment:
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-master}
      KEYCLOAK_URL: http://keycloak:${KEYCLOAK_PORT:-8180}/
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT:-spring-resources-server}
      RESOURCES_SERVICE_PORT: ${RESOURCES_SERVICE_PORT:-8084}
      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET:-nOgeUOAggL7xVhjHeFLMa24kjIxvjLDP}
    ports:
      - '${RESOURCES_SERVICE_PORT:-8084}:${RESOURCES_SERVICE_PORT:-8084}'
    networks:
      - keycloak-network
    depends_on:
      - keycloak

  keycloak:
    image: bitnami/keycloak:21.0.2-debian-11-r1
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_PORT: 5430
      KEYCLOAK_DATABASE_HOST: postgres-keycloak
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
      KEYCLOAK_HTTP_PORT: ${KEYCLOAK_PORT:-8180}
    ports:
      - "${KEYCLOAK_PORT:-8180}:${KEYCLOAK_PORT:-8180}"
      - "8443:8443"
    depends_on:
      - postgres-keycloak
      - user-service
    networks:
      - keycloak-network
      - user-service-network
    volumes:
      - ./user-provider/target/user-provider-0.0.1-SNAPSHOT-fat.jar:/opt/bitnami/keycloak/providers/custom-provider.jar

  postgres-keycloak:
    image: postgres:alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    command:
      -p 5430
    volumes:
      - db-keycloak:/var/lib/postgresql/data
    networks:
      - keycloak-network

networks:
  keycloak-network:
  user-service-network:

volumes:
  db:
    driver: local
  db-keycloak:
    driver: local
